### ISSUE TITLE
#52 - Error 500 when missing header

### ISSUE THREAD

**Issue by ibrahimcherni2018** [ReliefApplications/bms_api#53]
**Branch** : dev
**Commit before issue**: #52 

When hitting the api without the **country** header, we get an internal server error (500) instead of understabdable message. 

To fix it, we should handle this error with a listener or throw a custom exception on the code that handle the header.

**Comment by bamoure** [comment]
Fixed with commit ce79d1e5a5f2b045ca814d0740682de559eaad2b
Now returns bad request error with clear message
